jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          environment-name: genomextract
          cache-downloads: true
          cache-env: true
          channels: conda-forge,bioconda

      - name: Activate environment and install package
        shell: bash -l {0}
        run: |
          micromamba activate genomextract
          python -m pip install .

      - name: Test CLI tools
        shell: bash -l {0}
        run: |
          micromamba activate genomextract
          findGenome --help
          findClosestGenome --help
          assembleOrgGenome --help
          assembleOrgGenes --help

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba activate genomextract
          pytest -q
